project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Bioinformatics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lectures.qmd
      - resources.qmd
      - project.qmd

format:
  html:
    theme: Zephyr
    toc: true
    css: styles.css



