project:
  type: website
  output-dir: docs

website:
  title: "ITB 2025"
  navbar:
    search: true
    right:
      - icon: house
        text: "Home"
        file: index.qmd
      - icon: book
        text: "Lectures"
        href: lectures.qmd
      - icon: pencil
        text: "Assignments"
        href: assignments.qmd
      - icon: clipboard2
        text: "Project"
        href: project.qmd
      - icon: archive
        text: "Resources"
        href: resources.qmd

format:
  html:
    theme: styles.scss
    toc: true

execute:
  freeze: auto


